[build]
  publish = "out"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  NPM_FLAGS = "--production=false"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
