[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
